### PR TITLE
[1.x] Add authorization checker

### PR DESCRIPTION
**Pull request by imdhemy**
| Q             | A                                                                  |
|---------------|--------------------------------------------------------------------|
| Branch?       | 1.x                                              |
| Bug fix?      | no                                                            |
| New feature?  | yes                   |
| Deprecations? | no  |
| Tickets       | N/A            |
| License       | MIT                                                                |

This PR adds an **Authorization Checker** to the **Security** namespace. It could be used along with [Voters](https://symfony.com/doc/current/security/voters.html) to authorize access to different API resources. In case of failure, it throws an `AccessDeniedException` which is rendered as a `403` Forbidden response.

The Authorization checker interface could be injected into actions and it provides two methods:

```php 
class MyAction {
      public function execute(): MyResource 
      {
           // To check if a permission is granted
           if($this->authChecker->isGranted('edit', $box){
             // do some stuff
           }

          // To fail if not authorized
         $this-> denyAccessUnlessGranted('edit', $box);
      }
}
```

The `isGranted()` method only returns a `boolean`, but the `denyAccessUnlessGranted()` method throws an exception if the active user is not granted the permission to perform the specified action on the specified resource.

### CODE REVIEW

**Comment by imdhemy** [comment]
Could you please review this PR? @mgamal92 @Moemen-Gaballah

**Review by Moemen-Gaballah — APPROVED** [review]
Good.

**Comment by mgamal92** [comment]
@imdhemy Could you write more details about this PR ?

**Comment by imdhemy** [comment]
@mgamal92 updated the description...

**Comment by imdhemy** [comment]
As per our call yesterday, I'm going to merge this. @mgamal92

**Comment by mgamal92** [comment]
> As per our call yesterday, I'm going to merge this. @mgamal92

Sorry to forget that. BTW Great Work @imdhemy

**Pull request merged**
